<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
	<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
		<div class="loader">
			<img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
			alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
			style="position: absolute;">
		</div>
	</div>
	<!-- ko template: getTemplate() --><!-- /ko -->
	<script type="text/x-magento-init">
		{
			"#checkout": {
			"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
		}
	}
</script>
<script>
	window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
		// Create aliases for customer.js model from customer module
		window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
		window.customerData = window.checkoutConfig.customerData;
	</script>
	<script>
		require([
			'mage/url',
			'Magento_Ui/js/block-loader'
			], function(url, blockLoader) {
				blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
				return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
			})
		</script>

		<script type="text/javascript">
			
			require(["jquery"],function($) {
				// $(document).ready(function() {

					jQuery(document).on('change',"[name='country_id']",function(){

						var country_id=jQuery(this).val();

						if(country_id==''){
							jQuery('div[name="shippingAddress.city"]').hide();
							//jQuery('select[name="city"]').hide();

						}
						else{

							var customurl = "";



							$.ajax({
								url: customurl,
								type: 'POST',
								dataType: 'json',
								data: {
									country_id: country_id
								},
								complete: function(response) {             
							// country = response.responseJSON.default_country;
							// state = response.responseJSON.state;         
							console.log('completed');   
							jQuery('div[name="shippingAddress.city"]').show();
							//jQuery('select[name="city"]').show();


						},
						error: function (xhr, status, errorThrown) {
							console.log('Error happens. Try again.');
						}
					});


						}
					});



				// });
			});
		</script>

	</div>
